name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node_version: [12]
 
    runs-on: macOS-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
      env:
        node_version: 12
    - name: Build
      run: |
        npm install nativefier -g
        ./build.sh
        tar -czvf "Google Calendar-darwin-x64.tar.gz" "Google Calendar-darwin-x64"
    - name: Release
      uses: docker://softprops/action-gh-release
      with:
        body_path: "Google Calendar-darwin-x64.tar.gz"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
